# Generated by Django 5.0.4 on 2024-04-21 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=255)),
                ('poet_description', models.CharField(max_length=255)),
                ('poet_image', models.ImageField(upload_to='poet_images')),
                ('poet_about', models.TextField()),
                ('poet_birthdate', models.CharField(max_length=11)),
                ('poet_dead_date', models.CharField(max_length=11)),
                ('poet_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Poets',
                'db_table': 'poets',
            },
        ),
        migrations.CreateModel(
            name='PoemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_name', models.CharField(max_length=255)),
                ('poem_poem', models.TextField()),
                ('poem_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poem_poet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzbek_poets_app.poetsmodel')),
            ],
            options={
                'verbose_name_plural': 'Poems',
                'db_table': 'poems',
            },
        ),
    ]
