# Generated by Django 5.0.4 on 2024-05-10 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsmodel',
            name='standard_year',
            field=models.CharField(default='2023', max_length=15),
        ),
        migrations.AlterField(
            model_name='standardsmodel',
            name='standard_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
