# Generated by Django 5.0.4 on 2024-05-10 15:29

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standards', '0003_alter_standardsmodel_standard_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicStandardTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_standard_type', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Electronic Standards Types',
                'db_table': 'ElectronicStandardsTypes',
            },
        ),
        migrations.CreateModel(
            name='ElectronicStandardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_code', models.CharField(max_length=55)),
                ('standard_description', models.CharField(max_length=255)),
                ('standard_text', ckeditor.fields.RichTextField(null=True)),
                ('standard_file', models.FileField(null=True, upload_to='Standards/%y/%m/%d/')),
                ('standard_year', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_standards.electronicstandardtypesmodel')),
            ],
            options={
                'verbose_name_plural': 'Electronic Standards',
                'db_table': 'electronic_standards',
            },
        ),
    ]
