# Generated by Django 5.0.4 on 2024-05-10 18:05

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_NLS', '0002_structuralunitsmodel'),
        ('app_standards', '0004_electronicstandardtypesmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRegulationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.IntegerField()),
                ('doc_type', models.CharField(max_length=20)),
                ('doc_code', models.CharField(max_length=20)),
                ('doc_title', models.CharField(max_length=255)),
                ('doc_text', ckeditor.fields.RichTextField()),
                ('doc_file', models.FileField(null=True, upload_to='BuildingRegulations/%y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Building Regulations',
                'db_table': 'building_regulations',
            },
        ),
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_fio', models.CharField(max_length=255)),
                ('msg_email', models.EmailField(max_length=254)),
                ('msg_phone_number', models.CharField(max_length=20)),
                ('msg_text', models.TextField()),
                ('msg_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_NLS.leadershipmodel')),
            ],
        ),
    ]
