# Generated by Django 5.0.4 on 2024-05-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_standards', '0005_buildingregulationsmodel_messagesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesmodel',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelTable(
            name='messagesmodel',
            table='messages',
        ),
    ]
