# Generated by Django 5.0.6 on 2024-05-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 5, 26, 692145)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetmodel',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 5, 26, 694258)),
        ),
    ]
