# Generated by Django 5.0.6 on 2024-05-26 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 35, 32, 399306)),
        ),
        migrations.AlterField(
            model_name='passwordresetmodel',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 35, 32, 402159)),
        ),
    ]
