# Generated by Django 5.0.4 on 2024-05-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_title', models.CharField(max_length=255)),
                ('ann_description', models.CharField(max_length=500)),
                ('ann_text', models.TextField()),
                ('ann_image', models.ImageField(null=True, upload_to='news/%y/%m/%d/')),
                ('ann_datetime', models.DateTimeField(auto_now=True)),
                ('ann_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'announcements',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='LeadershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('reception_days', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bachelor', models.CharField(max_length=50, null=True)),
                ('master', models.CharField(max_length=50, null=True)),
                ('doctoral', models.CharField(max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'leadership',
                'db_table': 'leadership',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.CharField(max_length=500)),
                ('news_text', models.TextField()),
                ('news_image', models.ImageField(upload_to='news/%y/%m/%d/')),
                ('news_datetime', models.DateTimeField(auto_now=True)),
                ('news_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
    ]
