# Generated by Django 5.0.4 on 2024-05-12 17:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPartsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=255)),
                ('part_text', ckeditor.fields.RichTextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=10)),
                ('doc_title', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to='docs/%y/%m/%d/')),
                ('doc_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=255)),
                ('plan_text', ckeditor.fields.RichTextField(null=True)),
                ('plan_subplan', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan_part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documentpartsmodel')),
                ('plan_doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documentsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='documentpartsmodel',
            name='part_doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documentsmodel'),
        ),
        migrations.CreateModel(
            name='DocumentSubPlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subplan_title', models.CharField(max_length=255)),
                ('subplan_text', ckeditor.fields.RichTextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documentsmodel')),
                ('doc_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documentplanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='doc_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.documenttypesmodel'),
        ),
        migrations.CreateModel(
            name='GroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='doc_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.groupsmodel'),
        ),
        migrations.CreateModel(
            name='SubsystemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=10)),
                ('sub_name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupsmodel',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_subsystems.subsystemsmodel'),
        ),
    ]
