# Generated by Django 5.0.4 on 2024-05-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subsystems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpartsmodel',
            options={'verbose_name_plural': 'Documnet Parts'},
        ),
        migrations.AlterModelOptions(
            name='documentplanmodel',
            options={'verbose_name_plural': 'DouPlans'},
        ),
        migrations.AlterModelOptions(
            name='documentsmodel',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentsubplansmodel',
            options={'verbose_name_plural': 'DocSubPlans'},
        ),
        migrations.AlterModelOptions(
            name='documenttypesmodel',
            options={'verbose_name_plural': 'DocTypes'},
        ),
        migrations.AlterModelOptions(
            name='groupsmodel',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='subsystemsmodel',
            options={'verbose_name_plural': 'Subsystems'},
        ),
        migrations.AlterModelTable(
            name='documentpartsmodel',
            table='document_parts',
        ),
        migrations.AlterModelTable(
            name='documentplanmodel',
            table='doc_plans',
        ),
        migrations.AlterModelTable(
            name='documentsmodel',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='documentsubplansmodel',
            table='doc_subplans',
        ),
        migrations.AlterModelTable(
            name='documenttypesmodel',
            table='doc_types',
        ),
        migrations.AlterModelTable(
            name='groupsmodel',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='subsystemsmodel',
            table='Subsystems',
        ),
        migrations.CreateModel(
            name='DictionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_code', models.CharField(max_length=50)),
                ('dict_uz', models.CharField(max_length=255)),
                ('dict_tr', models.CharField(max_length=255)),
                ('dict_eng', models.CharField(max_length=255)),
                ('dict_ru', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dictionary',
                'db_table': 'dictionary',
            },
        ),
    ]
