# Generated by Django 5.0.6 on 2024-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=765)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('info', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
