# Generated by Django 5.0.6 on 2024-05-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_rename_categories_categoriesmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='category',
            new_name='category_id',
        ),
    ]
