# Generated by Django 5.0.6 on 2024-05-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_rename_category_productsmodel_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='urls',
        ),
    ]
