# Generated by Django 5.0.6 on 2024-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_remove_productsmodel_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='old_price',
            field=models.FloatField(null=True),
        ),
    ]
